import React, { Component } from "react";
import axios from "axios";
import Information from "../../../components/information/information";
import CONFIG from "../../../config.json";
import Translations from "../../../translations.json";

class AiSummary extends Component {
  state = {
    summary: false,
  };
  async componentDidMount() {
    const { lake } = this.props;
    try {
      const { data } = await axios.get(
        CONFIG.alplakes_bucket + `/aisummary/${lake}/forecast.json`
      );
      this.setState({ summary: data });
    } catch (e) {
      console.error(e);
    }
  }
  render() {
    var { language } = this.props;
    var { summary } = this.state;
    if (summary !== false) {
      return (
        <div className="aisummary subsection">
          <h3>
            {Translations.overview[language]}
            <Information
              information={
                "AI generated overview of the forecasted conditions for the lake."
              }
            />
          </h3>
          <p>{summary["data"][language]}</p>
          <div className="subtext">
            Generated by {summary["model"]}. Something wrong? Report it{" "}
            <a href="mailto:james.runnalls@eawag.ch">here</a>.
          </div>
        </div>
      );
    }
  }
}

export default AiSummary;
